export const ROTULO_CADU: Record<string, string> = {
  masculino: "Masculino",
  feminino: "Feminino",
  nao_informado: "Não informado",
  branca: "Branca",
  preta: "Preta",
  amarela: "Amarela",
  parda: "Parda",
  indigena: "Indígena",
  outro_codigo: "Outro código",
  analfabeto: "Analfabeto",
  fundamental_incompleto: "Fundamental incompleto",
  fundamental_completo: "Fundamental completo",
  medio_incompleto: "Médio incompleto",
  medio_completo: "Médio completo",
  superior_incompleto: "Superior incompleto",
  superior_completo: "Superior completo",
  crianca_0_11: "0–11 anos",
  adolescente_12_17: "12–17 anos",
  adulto_18_59: "18–59 anos",
  idoso_60_mais: "60 anos ou mais",
  idade_nao_informada: "Idade não informada",
  sem_deficiencia: "Sem deficiência",
  deficiencia_fisica: "Deficiência física",
  deficiencia_visual: "Deficiência visual",
  deficiencia_auditiva: "Deficiência auditiva",
  deficiencia_mental_cognitiva: "Deficiência mental / cognitiva",
  deficiencia_multipla: "Deficiência múltipla",
  com_deficiencia_sem_tipo: "Com deficiência (tipo não detalhado)",
  com_deficiencia: "Com deficiência",
  renda_0_218: "R$ 0,00 a R$ 218,00",
  renda_219_810: "R$ 218,01 a R$ 810,00",
  renda_811_1621: "R$ 810,01 a R$ 1.621,00",
  renda_1622_3242: "R$ 1.621,01 a R$ 3.242,00",
  renda_acima_3242: "Acima de R$ 3.242,00",
  renda_nao_informada: "Renda não informada",
};

export function rotuloAmigavel(chave: string): string {
  return ROTULO_CADU[chave] ?? chave.replace(/_/g, " ");
}
